Add real price steering logic
vegaprotocol/liqbot pull request #46
Opened 2021-05-17 12:45 UTC by peterbarrow

Implement the price steering logic as defined in the liquidity bot spec.

2021-05-22 08:16 UTC, ashleyvega requested changes
Looking good, but changes suggested.

2021-05-22 08:16 UTC, ashleyvega commented on bot/normal/normal.go
> +	quote = "USD"
I would prefer to avoid defaults. If the base or quote cannot be found/deduced, feel free to `panic()`.

Also, what happens with markets (e.g. [AAPL](4899E01009F1A721), [TSLA](https://lb.testnet.vega.xyz/markets/5A86B190C384997F)) which have tags like `ticker:AAAA` and/or `country:GB`? 

See [traderbot:core/currencypair.go](https://github.com/vegaprotocol/traderbot/blob/63ffcb90c5387d13528270314a6f3e7bc2b488c3/core/currencypair.go#L14-L78) for how traderbot does it.

2021-05-22 08:16 UTC, ashleyvega commented on bot/normal/normal.go
> +							b.log.Fatalln("Unable to get realistic order details for price steering")
Please also print `priceError.Error()`.

2021-05-22 08:16 UTC, ashleyvega commented on bot/normal/normal.go
> +	err = nil
Var is already initialised to `nil`, I think.

2021-05-22 08:16 UTC, ashleyvega commented on bot/normal/normal.go
> +		err = errors.Wrap(err, "Method for generating price distributions not recognised")
As recommended by Jeremy, please switch to:
```go
err = fmt.Errorf("Method for generating price distributions not recognised: %w", err)
```

2021-05-22 08:16 UTC, ashleyvega commented on bot/normal/normal.go
> +		return 0, 0, err
Since you're using named return vars, you can just `return` on its own here.

2021-05-22 08:16 UTC, ashleyvega commented on bot/normal/normal.go
> +		return price, 1, err
Suggestion: 
Declare `priceFloat`, then switch ":=" to "=" so `err` is not redefined, so that the `return` statement can be simplified.

```go
var priceFloat float64
priceFloat, err = GeneratePriceUsingDiscreteThreeLevel(M0, delta, sigma, tgtTimeHorizonYrFrac, N)

// we need to add back decimals
price = uint64(math.Round(priceFloat * math.Pow(10, float64(b.market.DecimalPlaces))))
return
```

2021-05-22 08:16 UTC, ashleyvega commented on bot/normal/normal.go
> +		return externalPrice, 1, err
`err` should be `nil` at this point, so it may be clearer to `return externalPrice, 1, nil`

2021-05-24 12:10 UTC, peterbarrow commented on bot/normal/normal.go
> +	quote = "USD"
Handling all the possible combos seems hard work so I've added the option for the user to select the quote+base in the config but to lookup using the metadata if not supplied. This seems the only way to avoid recompiling to fix issues later.

2021-05-24 12:10 UTC, peterbarrow commented on bot/normal/normal.go
> +							b.log.Fatalln("Unable to get realistic order details for price steering")
Added, thanks

2021-05-24 12:10 UTC, peterbarrow commented on bot/normal/normal.go
> +	err = nil
Removed, thanks

2021-05-24 12:10 UTC, peterbarrow commented on bot/normal/normal.go
> +		err = errors.Wrap(err, "Method for generating price distributions not recognised")
Updated, thanks.

2021-05-24 12:10 UTC, ashleyvega commented on bot/normal/normal.go
> +	quote = "USD"
Good plan :+1:

2021-05-24 12:10 UTC, peterbarrow commented on bot/normal/normal.go
> +		return 0, 0, err
Updated, thanks

2021-05-24 12:11 UTC, peterbarrow commented on bot/normal/normal.go
> +		return price, 1, err
Updated, thanks.

2021-05-24 12:11 UTC, peterbarrow commented on bot/normal/normal.go
> +		return externalPrice, 1, err
Updated, thanks.

2021-05-24 12:54 UTC, ashleyvega approved these changes
LGTM

2021-05-24 13:13 UTC, merged